module JpPrefecture
  module Base
  end

  self.@config: ReJpPrefecture::Config?

  def self.config: () -> ReJpPrefecture::Config
  def self.setup: () { (ReJpPrefecture::Config) -> void } -> void
  def self.included: (Module base) -> void
end
